//Bookings
export const BOOKINGS_SEARCH_DAYS = 365

export const UPDATE_PRICE_DISTANCE_FACTOR = 0.9

//Subscription
export const TRIAL_DAYS = 60

export const EXISTING_ORDER_SEARCH_HOURS = 24

export const MONTHLY_SUBSCRIPTION_DAYS = 30
export const QUARTERLY_SUBSCRIPTION_DAYS = 90
export const ANNUAL_SUBSCRIPTION_DAYS = 365

//Billing
export const MONTHLY_SUBSCRIPTION_MRP = 999
export const QUARTERLY_SUBSCRIPTION_MRP = 2999
export const ANNUAL_SUBSCRIPTION_MRP = 11999

export const MONTHLY_SUBSCRIPTION_FINAL_PRICE = 499
export const QUARTERLY_SUBSCRIPTION_FINAL_PRICE = 1399
export const ANNUAL_SUBSCRIPTION_FINAL_PRICE = 4999

export const GST_PERCENTAGE = 18

//Route
export const MIN_USER_DISTANCE_RATIO = 0.8
export const MAX_USER_DISTANCE_RATIO = 1.2
