import z from "zod"

const getStringRegex = (length: number) => z.string().trim().length(length)

export const AgencyRegex = getStringRegex(8).regex(/A\d{7}/)
export const OrderRegex = getStringRegex(8).regex(/O\d{7}/)
export const PaymentRegex = getStringRegex(8).regex(/P\d{7}/)
export const UserRegex = getStringRegex(8).regex(/U\d{7}/)
export const SessionRegex = getStringRegex(8).regex(/S\d{7}/)
export const RouteRegex = getStringRegex(8).regex(/R\d{7}/)
export const LocationRegex = getStringRegex(8).regex(/L\d{7}/)
export const VehicleRegex = getStringRegex(8).regex(/V\d{7}/)
export const DriverRegex = getStringRegex(8).regex(/D\d{7}/)
export const CustomerRegex = getStringRegex(8).regex(/C\d{7}/)
export const BookingRegex = getStringRegex(8).regex(/B\d{7}/)
export const TransactionRegex = getStringRegex(8).regex(/T\d{7}/)
export const ExpenseRegex = getStringRegex(8).regex(/E\d{7}/)
export const VehicleRepairRegex = getStringRegex(9).regex(/VR\d{7}/)
export const DriverLeaveRegex = getStringRegex(9).regex(/DL\d{7}/)
export const TripLogRegex = getStringRegex(9).regex(/TL\d{7}/)
export const MissionRegex = getStringRegex(8).regex(/M\d{7}/)
export const NotificationRegex = getStringRegex(8).regex(/N\d{7}/)

export const PhoneRegex = getStringRegex(10).regex(/^[0-9]+$/)
export const EmailRegex = z.email()
export const PasswordRegex = z.string().trim().min(8)
